# -*- coding: utf-8 -*-
"""SF_Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oV4yTLcORV98ucFwvea9pMtmbwiy6tHg
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
import numpy as np
df= pd.read_csv('/content/gdrive/MyDrive/Dataset/Iris.csv')
df= df.drop('Species', axis=1)

df.head(5)

df.isnull().sum()

x= df.iloc[:, 1:5]
x

from sklearn.cluster import KMeans
x = df.iloc[:, [0, 1, 2, 3]].values
kmeans = KMeans(n_clusters = 3,init = 'k-means++',
                max_iter = 300, n_init = 10, random_state = 0)
y_kmeans = kmeans.fit_predict(x)

df["clusters"] = y_kmeans
df.head()

#Visualising the clusters
plt.scatter(x[y_kmeans == 0, 0], x[y_kmeans == 0, 1], s = 100, c = 'purple', label = 'Iris-setosa')
plt.scatter(x[y_kmeans == 1, 0], x[y_kmeans == 1, 1], s = 100, c = 'orange', label = 'Iris-versicolour')
plt.scatter(x[y_kmeans == 2, 0], x[y_kmeans == 2, 1], s = 100, c = 'green', label = 'Iris-virginica')

#Plotting the centroids of the clusters
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:,1], s = 100, c = 'red', label = 'Centroids')

plt.legend()